version: '3.8'

services:
  app:
    build: .
    container_name: d2-rage-counter-app
    restart: unless-stopped
    # --- FIX: Explicitly set the environment to production ---
    environment:
      - NODE_ENV=production
    # ---------------------------------------------------------
    networks:
      - d2-network
      - mysql_network
    env_file:
      - ./.env

  nginx:
    image: nginx:1.25-alpine
    container_name: d2-nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    networks:
      - d2-network
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: d2-certbot
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    networks:
      - d2-network
    command: renew

networks:
  d2-network:
    driver: bridge
  mysql_network:
    external: true