version: '3.8'

services:
  app:
    build: .
    container_name: d2-rage-counter-app
    restart: unless-stopped
    networks:
      - app-network
    # FIX: Load all environment variables from the .env file
    env_file:
      - ./.env

  nginx:
    image: nginx:1.25-alpine
    container_name: d2-nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount our generated Nginx config, Certbot webroot, and the certificates
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    networks:
      - app-network
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: d2-certbot
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    # This command runs 'certbot renew' twice a day to keep certs fresh.
    command: renew

networks:
  app-network:
    driver: bridge