version: '3.8'

services:
  app:
    build: .
    container_name: d2-rage-counter-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=your-very-strong-and-long-random-secret-for-production # Make sure this is a unique, random string
      # FIX 1: Use the container name for the host, not the public IP.
      - DB_HOST=mysql_container
      - DB_USER=root
      - DB_PASSWORD=8FwP9RjqGpjRXNS8fnUKeY9iWmSExQCbwhwEaeQS30x14pw71kByAipH7tsKaIJCfjuLWWS8
      - DB_NAME=d2_rage_counter
      - DB_PORT=3306
      # FIX 2: Add a variable to control secure cookies.
      # Set to 'false' for testing over HTTP. Set to 'true' when you have HTTPS.
      - COOKIE_SECURE=false
    networks:
      - mysql_network

networks:
  mysql_network:
    external: true